swagger: '2.0'
info:
  title: Example Gateway
  description: API Gateway with firebase auth
  version: 1.1.0
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  firebase:
    authorizationUrl: ''
    flow: implicit
    type: oauth2
    x-google-issuer: "https://securetoken.google.com/tiira-watcher-dev"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "${project}"
x-google-endpoints:
  - name: https://api-gw-8jy625wu.ew.gateway.dev
    allowCors: True
paths:
  /sightings:
    get:
      security:
        - firebase: []
      description: Get all sightings within time period, default 1 day
      operationId: get-sightings
      responses:
        '200':
          description: Success
      x-google-backend:
        address: "${api_endpoint}/sightings"
    options:
      description: Get all sightings CORS preflight request
      operationId: options-sightings
      responses:
        '200':
          description: Success
      x-google-backend:
        address: "${api_endpoint}/sightings"
  /search:
    post:
      security:
        - firebase: []
      description: Post new search request
      operationId: post-search
      responses:
        '200':
          description: Success
      x-google-backend:
        address: "${api_endpoint}/search"
    options:
      description: Get all sightings CORS preflight request
      operationId: options-search
      responses:
        '200':
          description: Success
      x-google-backend:
        address: "${api_endpoint}/search"