name: "Terraform deployment to GCP"

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      GCR_PROJECT:
        required: true
      TERRAFORM_SA_KEY:
        required: true
      TERRAFORM_VARS:
        required: true
  
jobs:
  terraform-apply:
    name: "Terraform apply job"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.TERRAFORM_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get last built version files
        run: |
          gcloud storage cp gs://${{ secrets.GCR_PROJECT }}-terraform-backend/app_versions/server_version.txt terraform/
          gcloud storage cp gs://${{ secrets.GCR_PROJECT }}-terraform-backend/app_versions/ui_version.txt terraform/
          echo "Server version: $(cat terraform/server_version.txt)"
          echo "UI version: $(cat terraform/ui_version.txt)"

      - name: Bring GCP service account key from github secrets
        working-directory: ./terraform
        run: |
          echo "$GCP_KEY" > gcp-credentials.json        # Dev
          echo "$GCP_KEY" > tiira-watcher-prod-sa.json  # Prod
        env:
          GCP_KEY: ${{secrets.TERRAFORM_SA_KEY}}

      - name: Bring terraform vars from github secrets
        working-directory: ./terraform
        run: 'echo "$VARS" > gcr.tfvars'
        env:
          VARS: ${{secrets.TERRAFORM_VARS}}

      - name: Generate terraform backend config
        working-directory: ./terraform
        run: 'echo "bucket = \"${{secrets.GCR_PROJECT }}-terraform-backend\"" > terraform.config'

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -reconfigure --backend-config=./terraform.config
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "./gcp-credentials.json"

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve -var-file=gcr.tfvars
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "./gcp-credentials.json"
