name: "Terraform deployment to GCP"

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    name: "Terraform apply job"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main

      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get last built version files
        run: |
          gcloud storage cp gs://${{ secrets.GCR_PROJECT }}-terraform-backend/app_versions/server_version.txt terraform/
          gcloud storage cp gs://${{ secrets.GCR_PROJECT }}-terraform-backend/app_versions/ui_version.txt terraform/
          echo "Server version: $(cat terraform/server_version.txt)"
          echo "UI version: $(cat terraform/ui_version.txt)"

      - name: Bring GCP service account key from github secrets
        working-directory: ./terraform
        run: 'echo "$GCP_KEY" > gcp-credentials.json'
        env:
          GCP_KEY: ${{secrets.GCR_SA_KEY}}

      - name: Bring terraform vars from github secrets
        working-directory: ./terraform
        run: 'echo "$VARS" > gcr.tfvars'
        env:
          VARS: ${{secrets.TERRAFORM_VARS}}

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -reconfigure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "./gcp-credentials.json"

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve -var-file=gcr.tfvars
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "./gcp-credentials.json"
